INSERT INTO users (
    email,
    hashed_password,
    first_name,
    last_name,
    is_admin,
    is_active
)
VALUES
(
    'admin@luxlumina.com',
    '$2b$10$7Q8qZq8QJYwNDUV7HURjE.gZl5d.kaXx2F5TJxCJQ9V0Fh6cZMTom',
    'Admin',
    'Lumina',
    TRUE,
    TRUE
),
(
    'demo@luxlumina.com',
    '$2b$10$7Q8qZq8QJYwNDUV7HURjE.gZl5d.kaXx2F5TJxCJQ9V0Fh6cZMTom',
    'Demo',
    'User',
    FALSE,
    TRUE
)
ON CONFLICT (email) DO NOTHING;

INSERT INTO coupons (
    code,
    description,
    discount_type,
    discount_value,
    min_order_amount,
    is_active
)
VALUES
(
    'LUMINA15',
    '15% off your first order',
    'percent',
    15,
    0,
    TRUE
)
ON CONFLICT (code) DO NOTHING;

INSERT INTO products (
    name,
    slug,
    reference,
    marque,
    rubrique,
    categorie,
    famille,
    description,
    features,
    specs,
    url_image1,
    url_image2,
    url_image3,
    url_image4,
    price,
    sale_price,
    discount_percent,
    colors,
    sizes,
    stock,
    weight,
    badge,
    is_featured,
    is_new,
    is_bestseller,
    rating,
    reviews_count
)
VALUES
(
    'Suspension PARIS',
    'suspension-paris',
    'LX-001',
    'Lux Lumina',
    'Lighting',
    'pendant',
    'Pendant Lights',
    'Premium pendant light for modern interiors.',
    '["Adjustable height", "LED compatible", "Dimmable"]',
    '{"Material": "Brass", "Bulb Type": "E27"}',
    '/images/Pendant Lights/Elegant Dining Pendant/1.jpg',
    '/images/Pendant Lights/Elegant Dining Pendant/2.jpg',
    '/images/Pendant Lights/Elegant Dining Pendant/3.jpg',
    '/images/Pendant Lights/Elegant Dining Pendant/4.jpg',
    289,
    217,
    25,
    '["gold", "black"]',
    '["medium", "large"]',
    15,
    1.8,
    '-25%',
    TRUE,
    FALSE,
    TRUE,
    4.8,
    124
),
(
    'Suspension SEVEN BUBBLE',
    'suspension-seven-bubble',
    'LX-002',
    'Lux Lumina',
    'Lighting',
    'pendant',
    'Pendant Lights',
    'Cluster pendant light with a premium decorative finish.',
    '["Adjustable globes", "LED compatible", "Statement piece"]',
    '{"Material": "Steel and glass", "Bulb Type": "E14"}',
    '/images/Pendant Lights/Glass Cluster Pendant/1.jpg',
    '/images/Pendant Lights/Glass Cluster Pendant/2.jpg',
    '/images/Pendant Lights/Glass Cluster Pendant/3.jpg',
    '/images/Pendant Lights/Glass Cluster Pendant/4.jpg',
    445,
    356,
    20,
    '["black", "gold"]',
    '["medium", "large"]',
    8,
    3.2,
    'New',
    TRUE,
    TRUE,
    FALSE,
    4.6,
    87
),
(
    'Applique VERON BK',
    'applique-veron-bk',
    'LX-003',
    'Lux Lumina',
    'Lighting',
    'sconce',
    'Wall Sconces',
    'Elegant wall sconce for bedrooms, corridors and premium interiors.',
    '["Wall mounted", "Warm ambient light", "LED compatible"]',
    '{"Material": "Metal", "Bulb Type": "G9"}',
    '/images/Wall Sconces/Modern Wall Light/1.jpg',
    '/images/Wall Sconces/Modern Wall Light/2.jpg',
    '/images/Wall Sconces/Modern Wall Light/3.jpg',
    '/images/Wall Sconces/Modern Wall Light/4.jpg',
    198,
    148,
    25,
    '["white", "black", "gold"]',
    '["small", "medium"]',
    22,
    1.4,
    '-25%',
    FALSE,
    FALSE,
    TRUE,
    4.9,
    203
),
(
    'Suspension KAITEN',
    'suspension-kaiten',
    'LX-004',
    'Lux Lumina',
    'Lighting',
    'floor',
    'Floor Lamps',
    'Premium floor lamp with modern architectural lines.',
    '["Large format", "Modern design", "LED compatible"]',
    '{"Material": "Steel", "Bulb Type": "E27"}',
    '/images/Floor Lamps/Minimal Arc Lamp/1.jpg',
    '/images/Floor Lamps/Minimal Arc Lamp/2.jpg',
    '/images/Floor Lamps/Minimal Arc Lamp/3.jpg',
    '/images/Floor Lamps/Minimal Arc Lamp/4.jpg',
    520,
    390,
    25,
    '["black", "gold", "silver"]',
    '["large"]',
    6,
    8.5,
    'Best Seller',
    TRUE,
    FALSE,
    TRUE,
    4.7,
    318
)
ON CONFLICT (slug) DO NOTHING;