INSERT INTO products (
    name,
    slug,
    reference,
    marque,
    rubrique,
    categorie,
    famille,
    description,
    features,
    specs,
    url_image1,
    url_image2,
    url_image3,
    url_image4,
    url_image5,
    price,
    sale_price,
    discount_percent,
    colors,
    sizes,
    stock,
    weight,
    badge,
    is_featured,
    is_new,
    is_bestseller,
    rating,
    reviews_count
)
VALUES
(
    'Suspension GELLY BK',
    'suspension-gelly-bk',
    'LX-005',
    'Lux Lumina',
    'Lighting',
    'pendant',
    'Pendant Lights',
    'Vintage-inspired hanging light with warm metallic accents and a soft decorative glow.',
    '["Adjustable hanging cable", "LED compatible", "Warm decorative light"]'::jsonb,
    '{"Material": "Metal and glass", "Bulb Type": "E27"}'::jsonb,
    '/images/Pendant Lights/Minimal Hanging Light/1.jpg',
    '/images/Pendant Lights/Minimal Hanging Light/2.jpg',
    '/images/Pendant Lights/Minimal Hanging Light/3.jpg',
    '/images/Pendant Lights/Minimal Hanging Light/4.jpg',
    NULL,
    312,
    249,
    20,
    '["copper", "gold", "silver"]'::jsonb,
    '["small", "medium", "large"]'::jsonb,
    12,
    0.9,
    '-20%',
    FALSE,
    FALSE,
    FALSE,
    4.5,
    76
),
(
    'Suspension DESK V2',
    'suspension-desk-v2',
    'LX-006',
    'Lux Lumina',
    'Lighting',
    'floor',
    'Floor Lamps',
    'Slim modern floor lamp designed for clean interiors and comfortable ambient lighting.',
    '["Minimal profile", "Integrated LED look", "Ideal for living rooms"]'::jsonb,
    '{"Material": "Aluminium", "Light Source": "LED compatible"}'::jsonb,
    '/images/Floor Lamps/Luxury Living Lamp/1.jpg',
    '/images/Floor Lamps/Luxury Living Lamp/2.jpg',
    '/images/Floor Lamps/Luxury Living Lamp/3.jpg',
    '/images/Floor Lamps/Luxury Living Lamp/4.jpg',
    NULL,
    368,
    295,
    20,
    '["silver", "black", "gold"]'::jsonb,
    '["large"]'::jsonb,
    10,
    3.8,
    'New',
    FALSE,
    TRUE,
    FALSE,
    4.6,
    54
),
(
    'Applique KOOLMAN A',
    'applique-koolman-a',
    'LX-007',
    'Lux Lumina',
    'Lighting',
    'sconce',
    'Wall Sconces',
    'Elegant gold wall sconce for bedrooms, corridors and refined hospitality interiors.',
    '["Wall mounted", "Gold finish", "Warm ambient light"]'::jsonb,
    '{"Material": "Brass and fabric", "Bulb Type": "E14"}'::jsonb,
    '/images/Wall Sconces/Luxury Gold Sconce/1.jpg',
    '/images/Wall Sconces/Luxury Gold Sconce/2.jpg',
    '/images/Wall Sconces/Luxury Gold Sconce/3.jpg',
    '/images/Wall Sconces/Luxury Gold Sconce/4.jpg',
    NULL,
    235,
    188,
    20,
    '["gold", "black"]'::jsonb,
    '["small"]'::jsonb,
    18,
    1.1,
    '-20%',
    FALSE,
    FALSE,
    FALSE,
    4.7,
    145
),
(
    'Suspension GELLY WHITE',
    'suspension-gelly-white',
    'LX-008',
    'Lux Lumina',
    'Lighting',
    'table',
    'Table Lamps',
    'Soft white table lamp bringing organic warmth to nightstands, consoles and shelves.',
    '["Ceramic-inspired base", "Fabric shade", "Soft ambient lighting"]'::jsonb,
    '{"Material": "Ceramic and linen", "Bulb Type": "E27"}'::jsonb,
    '/images/Table Lamps/Ceramic Table Lamp/1.jpg',
    '/images/Table Lamps/Ceramic Table Lamp/2.jpg',
    '/images/Table Lamps/Ceramic Table Lamp/3.jpg',
    '/images/Table Lamps/Ceramic Table Lamp/4.jpg',
    NULL,
    175,
    131,
    25,
    '["white", "black", "gold"]'::jsonb,
    '["small", "medium"]'::jsonb,
    20,
    2.1,
    '-25%',
    FALSE,
    FALSE,
    FALSE,
    4.8,
    211
),
(
    'Plafonnier SPIRALO GOLD',
    'plafonnier-spiralo-gold',
    'LX-009',
    'Lux Lumina',
    'Lighting',
    'floor',
    'Floor Lamps',
    'Tripod-inspired gold floor lamp with a premium silhouette for modern living spaces.',
    '["Stable tripod base", "Warm shade", "Premium gold finish"]'::jsonb,
    '{"Material": "Brass and fabric", "Bulb Type": "E27"}'::jsonb,
    '/images/Floor Lamps/Tripod Floor Lamp/1.jpg',
    '/images/Floor Lamps/Tripod Floor Lamp/2.jpg',
    '/images/Floor Lamps/Tripod Floor Lamp/3.jpg',
    '/images/Floor Lamps/Tripod Floor Lamp/4.jpg',
    NULL,
    485,
    388,
    20,
    '["gold", "black"]'::jsonb,
    '["large"]'::jsonb,
    7,
    4.2,
    'Best Seller',
    TRUE,
    FALSE,
    TRUE,
    4.9,
    267
),
(
    'Suspension BOSTON BK',
    'suspension-boston-bk',
    'LX-010',
    'Lux Lumina',
    'Lighting',
    'table',
    'Table Lamps',
    'Compact black accent lamp with industrial inspiration and decorative presence.',
    '["Accent lighting", "Modern black finish", "LED compatible"]'::jsonb,
    '{"Material": "Metal and glass", "Bulb Type": "E27"}'::jsonb,
    '/images/Table Lamps/Glass Accent Lamp/1.jpg',
    '/images/Table Lamps/Glass Accent Lamp/2.jpg',
    '/images/Table Lamps/Glass Accent Lamp/3.jpg',
    '/images/Table Lamps/Glass Accent Lamp/4.jpg',
    NULL,
    148,
    111,
    25,
    '["black", "copper"]'::jsonb,
    '["small", "medium"]'::jsonb,
    16,
    0.5,
    '-25%',
    FALSE,
    FALSE,
    FALSE,
    4.4,
    98
),
(
    'Suspension BOSTON WH',
    'suspension-boston-wh',
    'LX-011',
    'Lux Lumina',
    'Lighting',
    'table',
    'Table Lamps',
    'Luxury marble-inspired table lamp with a refined finish for premium interiors.',
    '["Luxury decorative base", "Soft shade", "Ideal for desks and bedside tables"]'::jsonb,
    '{"Material": "Marble and metal", "Light Source": "LED compatible"}'::jsonb,
    '/images/Table Lamps/Luxury Marble Lamp/1.jpg',
    '/images/Table Lamps/Luxury Marble Lamp/2.jpg',
    '/images/Table Lamps/Luxury Marble Lamp/3.jpg',
    '/images/Table Lamps/Luxury Marble Lamp/4.jpg',
    NULL,
    225,
    169,
    25,
    '["silver", "black", "gold"]'::jsonb,
    '["small"]'::jsonb,
    11,
    1.3,
    'New',
    FALSE,
    TRUE,
    FALSE,
    4.7,
    62
),
(
    'Suspension ZLATAN',
    'suspension-zlatan',
    'LX-012',
    'Lux Lumina',
    'Lighting',
    'sconce',
    'Wall Sconces',
    'Minimal matte wall sconce with a clean silhouette and soft architectural lighting.',
    '["Matte finish", "Wall mounted", "Warm indirect glow"]'::jsonb,
    '{"Material": "Metal", "Bulb Type": "E27"}'::jsonb,
    '/images/Wall Sconces/Minimal Matte Sconce/1.jpg',
    '/images/Wall Sconces/Minimal Matte Sconce/2.jpg',
    '/images/Wall Sconces/Minimal Matte Sconce/3.jpg',
    '/images/Wall Sconces/Minimal Matte Sconce/4.jpg',
    NULL,
    195,
    156,
    20,
    '["copper", "gold"]'::jsonb,
    '["small", "medium", "large"]'::jsonb,
    14,
    0.7,
    '-20%',
    FALSE,
    FALSE,
    FALSE,
    4.6,
    149
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    reference = EXCLUDED.reference,
    marque = EXCLUDED.marque,
    rubrique = EXCLUDED.rubrique,
    categorie = EXCLUDED.categorie,
    famille = EXCLUDED.famille,
    description = EXCLUDED.description,
    features = EXCLUDED.features,
    specs = EXCLUDED.specs,
    url_image1 = EXCLUDED.url_image1,
    url_image2 = EXCLUDED.url_image2,
    url_image3 = EXCLUDED.url_image3,
    url_image4 = EXCLUDED.url_image4,
    url_image5 = EXCLUDED.url_image5,
    price = EXCLUDED.price,
    sale_price = EXCLUDED.sale_price,
    discount_percent = EXCLUDED.discount_percent,
    colors = EXCLUDED.colors,
    sizes = EXCLUDED.sizes,
    stock = EXCLUDED.stock,
    weight = EXCLUDED.weight,
    badge = EXCLUDED.badge,
    is_featured = EXCLUDED.is_featured,
    is_new = EXCLUDED.is_new,
    is_bestseller = EXCLUDED.is_bestseller,
    rating = EXCLUDED.rating,
    reviews_count = EXCLUDED.reviews_count,
    updated_at = NOW();